version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
    volumes:
      - /var/lib/mysql
  agorakit:
    image: qnib/plain-agorakit
    ports:
      - 8080:8080
    command: wait.sh
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
